-- 1. What is the total revenue generated by male and female customers ?
select gender, SUM(purchase_amount_usd) as revenue
from customer_data
group by gender;

-- 2. Which customers used discout but still spent more than average purchase amount ?
select customer_id, purchase_amount_usd 
from customer_data 
where discount_applied = 'Yes' and purchase_amount_usd >= (select AVG(purchase_amount_usd) from customer_data);

-- 3. Which are the top 10 products with highest average review rating
select top 10 item_purchased, ROUND(AVG(review_rating),2) as average_rating
from customer_data
group by item_purchased
order by AVG(review_rating) desc;

-- 4. Compare the average Purchase Amount between Standard and Express Shipping.
select shipping_type, AVG(purchase_amount_usd) as avg_purchase_amount
from customer_data
where shipping_type in ('Standard','Express')
group by shipping_type;

-- 5. Does subscribed customers spend more ? Compare the total revenue.
select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount_usd),2) as avg_spent,
SUM(purchase_amount_usd) as total_revenue
from customer_data
group by subscription_status;

-- 6. Which 5 products have highest percentage of purchases with discounts applied ?
select top 5 item_purchased,
CAST(
	SUM(case when discount_applied = 'Yes' then 1 else 0 end) * 100.0 / COUNT(*) as decimal(5,2)) as discount_rate
from customer_data
group by item_purchased 
order by discount_rate desc;

-- 7. Segment customers into New, Returning and Loyal based on total and previous purchases.
with customer_type as (
	select customer_id, previous_purchases,
	case when previous_purchases = 1 then 'New'
		 when previous_purchases between 2 and 10 then 'Returning'
		 else 'Loyal'
		 end as customer_segment
	from customer_data
)
select customer_segment, 
count(*) as number_of_customers
from customer_type
group by customer_segment;


-- 8. What are top 3 products purchased in each category ?
with item_counts as (
	select category, item_purchased, COUNT(customer_id) as total_orders,
	ROW_NUMBER() over(partition by category order by COUNT(customer_id) desc) as item_rank
	from customer_data
	group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

-- 9. Are customers who are repeat buyesr also likely to subscribe ?
select subscription_status,
COUNT(customer_id) as repeat_buyers
from customer_data
where previous_purchases > 5
group by subscription_status;

-- 10. What is the revenue contribution of each age group ?
select age_group,
SUM(purchase_amount_usd) as total_revenue
from customer_data
group by age_group
order by total_revenue desc;